/* SOKIVA resilient offline shell and notification navigation */
const CACHE_VERSION = 'sokiva-v2.12.1';
const APP_SHELL = [
  '/',
  '/index.html',
  '/shop.html',
  '/product.html',
  '/checkout.html',
  '/account.html',
  '/login.html',
  '/register.html',
  '/customer.html',
  '/seller.html',
  '/courier.html',
  '/admin.html',
  '/request.html',
  '/delivery.html',
  '/contact.html',
  '/faq.html',
  '/style.css',
  '/identity.css',
  '/audit.css',
